### ISSUE TITLE
tag missing?

### ISSUE THREAD

**Issue by rlzijdeman** [wxwilcke/datalegendtools#1]
Hi X, this is awesome. I've installed docker and used the instructions to 'pull', but received a somewhat different than anticipated response in the term:

```
richardz@macbook-pro-3 projects % docker pull wxwilcke/datalegend
Using default tag: latest
Error response from daemon: manifest for wxwilcke/datalegend:latest not found: manifest unknown: manifest unknown
```

**Comment by wxwilcke** [comment]
The tag 'latest' did indeed not exist yet; I had used a version number instead (1.0.0). I've now added an alias linking 'latest' to that version, so I believe it should work now.

**Comment by rlzijdeman** [comment]
Great this now works. Docker uses 'latest' as default tag, as I obviously would not have thought of that :P
