### ISSUE TITLE
run: resource not found or authorization error?

### ISSUE THREAD

**Issue by rlzijdeman** [wxwilcke/datalegendtools#2]
Hi,

after having created the 'shared' directory (and not moving into it), I ran the second line from the documentation and received what appears to be a resource not found or authorization error:

```
richardz@macbook-pro-3 dataLegendPlayGround % docker run --rm -p 3000:3000 -it --mount type=bind,source=$PWD/shared,target=/home/datalegend/shared -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) datalegend
Unable to find image 'datalegend:latest' locally
docker: Error response from daemon: pull access denied for datalegend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by rlzijdeman** [comment]
I think I made the 'shared' directory in the wrong place. But how do I create a shared directory in /home/datalegend/ within docker?

**Comment by wxwilcke** [comment]
The 'shared' directory is already created within the container; the purpose of the argument `--mount type=bind,source=$PWD/shared,target=/home/datalegend/shared` is to mount the 'shared' directory at the current location ($PWD) on the host to the directory with the same name in the container. You can try to leave out the mount argument if you believe the error originates from that, although you cannot share any files between the host and the container if you do so.

However, the error message that you posted does not seem to point towards that being the issue though. Rather, it cannot locate the correct image. Could you try the following command instead:

    docker run --rm -p 3000:3000 -it --mount type=bind,source=$PWD/shared,target=/home/datalegend/shared -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) wxwilcke/datalegend

If the above doesn't work either, could you paste the output of `docker images`.
