### ISSUE TITLE
issue 'manual setup' workflow

### ISSUE THREAD

**Issue by rlzijdeman** [wxwilcke/datalegendtools#3]
Hi, I followed the instructions to run the 'Manual Setup'. At the point where I need to run

`# docker run --rm -p 3000:3000 -it --mount type=bind,source=$PWD/shared,target=/home/datalegend/shared -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) wxwilcke/datalegend`

I get the response 'docker command not found'.

**Comment by wxwilcke** [comment]
Hi Richard,

This response appears when Docker isn't installed. You can find instructions on how to install Docker on your device [here](https://docs.docker.com/get-docker/).

Best,
Xander

**Comment by rlzijdeman** [comment]
Hi, thanks, I by mistake executed the commands from within the docker instance :(
